# Generated by Django 3.2.5 on 2021-08-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20210803_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicilio',
            old_name='no_cale',
            new_name='no_calle',
        ),
    ]
